# Copied from https://docs.platformio.org/en/latest/ci/gitlab.html

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

# cache:
#  key: ${CI_JOB_NAME}

Build ESP32 ModbusServerExample:
  image: python:2.7
  stage: build
  tags: 
    - docker 
  script:
    - ls 
    - ls xxx
    - ls cas-modbus-stack/
    - ls cas-modbus-stack/source/
    - ls cas-modbus-stack/submodules/cas-common/source/
    # Move the files 
    - mkdir lib/casmodbusstack/
    - mv cas-modbus-stack/source/* lib/casmodbusstack/    
    - mv cas-modbus-stack/adapters/cpp/* lib/casmodbusstack/
    - mv cas-modbus-stack/submodules/cas-common/source/ChipkinEndianness*.* lib/casmodbusstack/
    # Debug 
    - ls lib/casmodbusstack/
