# Copied from https://docs.platformio.org/en/latest/ci/gitlab.html

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

cache:
  key: ${CI_JOB_NAME}

Build ESP32 ModbusServerExample:
  image: python:2.7
  stage: build
  tags: 
    - docker 
  variables:
    PLATFORMIO_CI_EXTRA_ARGS: ""
    PLATFORMIO_CI_SRC: src
  before_script:
    # Update the build number 
    - echo -e "#define CI_PIPELINE_IID $CI_PIPELINE_IID\n" >src/CIBuildSettings.h 
    - "cat src/CIBuildSettings.h"
    # Install platformio
    - "pip install -U platformio"    
  script:
    - ls 
    - ls cas-modbus-stack/
    - ls cas-modbus-stack/source/
    - ls cas-modbus-stack/submodules/cas-common/source/
    # Move the files 
    - mkdir lib/casmodbusstack/
    - mv cas-modbus-stack/source/* lib/casmodbusstack/    
    - mv cas-modbus-stack/adapters/cpp/* lib/casmodbusstack/
    - mv cas-modbus-stack/submodules/cas-common/source/ChipkinEndianness*.* lib/casmodbusstack/
    # Debug 
    - ls lib/casmodbusstack/
    # Build 
    - "platformio ci --lib='.' --board=featheresp32 $PLATFORMIO_CI_EXTRA_ARGS"
  
  artifacts:
    paths:
      - .pioenvs/featheresp32/firmware.*