# Copied from https://docs.platformio.org/en/latest/ci/gitlab.html

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

cache:
  key: ${CI_JOB_NAME}

Build ESP32 ModbusServerExample:
  image: python:2.7
  stage: build
  tags: 
    - docker 
  before_script:
    # Update the build number 
    - echo -e "#define CI_PIPELINE_IID $CI_PIPELINE_IID\n" >src/CIBuildSettings.h 
    - "cat src/CIBuildSettings.h"
    # Install platformio. (Requires Python 2.7, see image above)
    - "pip install -U platformio"    
  script:
    # Debug 
    - ls 
    - ls cas-modbus-stack/
    - ls cas-modbus-stack/source/
    - ls cas-modbus-stack/submodules/cas-common/source/
    
    # Move the files 
    # The way that platforum.io works is that it will compile every file in the lib folder.
    # and the entire cas-modbus-stack has many dependencies, including unit testing frameworks. 
    # so we can't just put the entire cas-modbus-stack folder into the lib folder. We need to 
    # move the files that are needed into lib folder for the build. 
    - mkdir lib/cas-modbus-stack/
    - cp cas-modbus-stack/source/* lib/cas-modbus-stack/    
    - cp cas-modbus-stack/adapters/cpp/* lib/cas-modbus-stack/
    - cp cas-modbus-stack/submodules/cas-common/source/ChipkinEndianness*.* lib/cas-modbus-stack/

    # Debug 
    - ls lib/cas-modbus-stack/

    # Build 
    # More info about platformio https://docs.platformio.org/en/latest/userguide/cmd_ci.html 
    - "platformio ci --lib='lib/cas-modbus-stack' --board=featheresp32 src"

    # Debug 
    - ls .pioenvs/featheresp32/ -lh
  
  artifacts:
    paths:
      - .pioenvs/featheresp32/firmware*.*