# Copied from https://docs.platformio.org/en/latest/ci/gitlab.html

image: python:2.7

stages:
  - test

cache:
  key: ${CI_JOB_NAME}

.job_template: &pio_run
  script:
    - "platformio ci --lib='.' --board=featheresp32 $PLATFORMIO_CI_EXTRA_ARGS"

before_script:
  # update the build number 
  - echo -e "#define CI_PIPELINE_IID $CI_PIPELINE_IID\n" >src/CIBuildSettings.h 
  - "cat src/CIBuildSettings.h"
  # install platformio
  - "pip install -U platformio"

Build ESP32-ModbusServerExample:
  <<: *pio_run
  variables:
    PLATFORMIO_CI_EXTRA_ARGS: ""
    PLATFORMIO_CI_SRC: src